---
deployment:
  tasks:
    - export DEPLOYPATH=/home/d170647/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp reset_password.php $DEPLOYPATH
    - /bin/cp createAccount.php $DEPLOYPATH
    - /bin/cp nosotros.php $DEPLOYPATH
     
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r layaut $DEPLOYPATH
    - /bin/cp -r servicios $DEPLOYPATH
    