---
deployment:
  tasks:
    - export DEPLOYPATH=/home/a147409/public_html/
    - /bin/cp index.php $DEPLOYPATH
       - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp reset_password.php $DEPLOYPATH
    - /bin/cp createAccount.php $DEPLOYPATH
     
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r layaut $DEPLOYPATH
    - /bin/cp -r servicios $DEPLOYPATH
    